### ISSUE TITLE
Unable to reproduce bottleneck baseline result for benchmark paper

### ISSUE THREAD

**Issue by HenryJia** [flow-project/flow#862] opened 2020-03-10 00:04 UTC
The result I obtain from simply running the baseline for bottleck scenario in the current version of Flow does not seem to produce the same result as the benchmark paper. The result seems to be much much higher. I'm currently running it with
```
python -m flow.benchmarks.baselines.bottleneck0
```

**Comment by eugenevinitsky** [comment] 2020-03-10 00:06
Correct. To reproduce that result exactly you would have to roll back versions and as the version of SUMO has changed and the bottleneck curve is now different (due to SUMO handling merging differently now). We put the commit number in there if you want to reproduce exactly. Sorry for the trouble!

**Comment by eugenevinitsky** [comment] 2020-03-10 00:06
Correct. To reproduce that result exactly you would have to roll back versions and as the version of SUMO has changed and the bottleneck curve is now different (due to SUMO handling merging differently now). We put the commit number in there if you want to reproduce exactly. Sorry for the trouble!

**Comment by eugenevinitsky** [comment] 2020-03-10 00:07
We are in the process of upgrading the benchmarks but it's going to be a while.

**Comment by HenryJia** [comment] 2020-03-10 00:25
Got it, thanks. I'll see if I can sweep the flow rate a little myself and see what happens

**Comment by eugenevinitsky** [comment] 2020-03-11 21:26
Closing since I think this is answered.

**Closed by eugenevinitsky** 2020-03-11 21:26 UTC
