### ISSUE TITLE
rllib example after changing scenario

### ISSUE THREAD

**Issue by pnp91** [flow-project/flow#419] opened 2019-02-20 13:04 UTC
This is a: 
- [x] Question
- [x] Feature request

**Describe the issue**
Reusing the example of rllib(tried with stabilizing highway.py) with different scenario and environment but with the same algorithm. Used 5 "human"(IDM Controller) vehicles and 5 "rl"(RL Controller) vehicles. Did the following changes from the example:
1. Changed the scenario and environment to bottle neck scenario and bottle neck environment. 
2. Also included the additional_net_params required i.e., scaling and speed_limit. 
3. Then changed the inflows from "inflow_highway" and "inflow_merge" to "1" and "3".
4. Added env Params             "lane_change_duration": 5,
                                               "disable_tb": True,
                                               "disable_ramp_metering": True,
5. But the algorithm to setup_exps() is used the same.  

**To Reproduce**
Leave empty if not applicable.
1. File in which error occurred. 
2. Exact command that was run that caused the error to occur. 
3. Please attach the full error output log. 

**Expected behavior**
I expected the behavior to be the similar one as of "Stabilizing_highway" but with "bottle neck" projection. It was not possible to do training because of these errors. 

**Screenshots** Error output:
-----------------------------------------------------------------------------------------------------------------------
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/3 CPUs, 0/1 GPUs
Memory usage on this node: 8.4/33.7 GB
Result logdir: /home/niyathipriya/ray_results/stabilizing_open_network_merges
RUNNING trials:
 - PPO_BottleneckEnv-v0_0:	RUNNING, 5 failures: /home/niyathipriya/ray_results/stabilizing_open_network_merges/PPO_BottleneckEnv-v0_0_2019-02-20_13-52-00amqzv9ot/error_2019-02-20_13-54-04.txt

Closing connection to TraCI and stopping simulation.
Note, this may print an error message when it closes.
I0220 13:54:04.762437 16016 store.cc:599] Disconnecting client on fd 16
2019-02-20 13:54:10,459	WARNING ppo.py:146 -- By default, observations will be normalized with MeanStdFilter
Loading configuration... done.
Success.
Loading configuration... done.
2019-02-20 13:54:11,533	INFO policy_evaluator.py:264 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-02-20 13:54:11.533913: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-02-20 13:54:12,398	INFO multi_gpu_optimizer.py:74 -- LocalMultiGPUOptimizer devices ['/cpu:0']
Loading configuration... done.
Success.
Loading configuration... done.
Loading configuration... done.
Success.
Loading configuration... done.
2019-02-20 13:54:26,174	INFO policy_evaluator.py:264 -- Creating policy evaluation worker 2 on CPU (please ignore any CUDA init errors)
2019-02-20 13:54:26.175518: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-02-20 13:54:26,227	INFO policy_evaluator.py:264 -- Creating policy evaluation worker 1 on CPU (please ignore any CUDA init errors)
2019-02-20 13:54:26.228473: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading configuration... done.
Success.
Loading configuration... done.
Success.
Loading configuration... done.
Loading configuration... done.
2019-02-20 13:54:29,068	ERROR trial_runner.py:413 -- Error processing event.
Traceback (most recent call last):
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/worker.py", line 2132, in get
    raise value
ray.worker.RayTaskError: ray_worker (pid=16608, host=linuxpriya)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 284, in train
    result = Trainable.train(self)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 103, in _train
    fetches = self.optimizer.step()
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 125, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/optimizers/rollout.py", line 28, in collect_samples
    next_sample = ray.get(fut_sample)
ray.worker.RayTaskError: ray_worker (pid=16601, host=linuxpriya)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 368, in sample
    batches = [self.input_reader.next()]
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/offline/input_reader.py", line 31, in next
    batches = [self.sampler.get_data()]
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 65, in get_data
    item = next(self.rollout_provider)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 267, in _env_runner
    preprocessors, obs_filters, unroll_length, pack, callbacks)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 354, in _process_observations
    episode.last_action_for(agent_id),
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/episode.py", line 99, in last_action_for
    flat = _flatten_action(policy.action_space.sample())
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/gym/spaces/box.py", line 37, in sample
    return gym.spaces.np_random.uniform(low=self.low, high=self.high + (0 if self.dtype.kind == 'f' else 1), size=self.low.shape).astype(self.dtype)
  File "mtrand.pyx", line 1316, in mtrand.RandomState.uniform
OverflowError: Range exceeds valid bounds

Closing connection to TraCI and stopping simulation.
Note, this may print an error message when it closes.
2019-02-20 13:54:29,084	INFO trial_runner.py:450 -- Attempting to recover trial state from last checkpoint.
I0220 13:54:29.090139 16016 store.cc:599] Disconnecting client on fd 17
Closing connection to TraCI and stopping simulation.
Note, this may print an error message when it closes.
I0220 13:54:29.127265 16016 store.cc:599] Disconnecting client on fd 13

-----------------------------------------------------------------------------------------------------------------------

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS, Intel Xeon(R) processor with 64 bit
 - flow-0.2.0 version 

Kindly let me know if I had done any wrong. I am unable to debug this as the error message says error inside the installed packages of ray, which is wrong as it works for the same examples if the scenario and environment is unchanged.

Note : Can you add some more details for basics of these examples described if I want to create my own scenario and train the vehicles. Like what are the basic factors need to be taken care before I start writing my functions for creating my own env and scenario and to train with another algotithm. The
documentation states few information but as a new learner, I expect it to be well described with the basics. 

Any help would highly be appreciated so that I can learn the unknown as I am still a learner. 
Thanks & Regards,
pnp91

**Comment by AboudyKreidieh** [comment] 2019-02-21 10:26
hi @pnp91 I looked into this and it seems that `BottleneckEnv` is not designed to be used by RL experiments, but rather just for simulations; instead, you will want to use `BottleNeckAccelEnv`. This environment, however, seems to be missing some features. I've created a PR meant to fix these bugs (see the branch bottleneck_env_fix). From this branch, the following script (adapted from stabilizing_highway.py) should work:

```
"""Open merge example.

Trains a a small percentage of rl vehicles to dissipate shockwaves caused by
merges in an open network.
"""
import json

import ray
try:
    from ray.rllib.agents.agent import get_agent_class
except ImportError:
    from ray.rllib.agents.registry import get_agent_class
from ray.tune import run_experiments
from ray.tune.registry import register_env

from flow.utils.registry import make_create_env
from flow.utils.rllib import FlowParamsEncoder
from flow.core.params import SumoParams, EnvParams, InitialConfig, NetParams, \
    InFlows, SumoCarFollowingParams
from flow.scenarios.bottleneck import ADDITIONAL_NET_PARAMS
from flow.core.params import VehicleParams
from flow.controllers import IDMController, RLController

# experiment number
# - 0: 10% RL penetration,  5 max controllable vehicles
# - 1: 25% RL penetration, 13 max controllable vehicles
# - 2: 33% RL penetration, 17 max controllable vehicles
EXP_NUM = 0

# time horizon of a single rollout
HORIZON = 600
# number of rollouts per training iteration
N_ROLLOUTS = 20
# number of parallel workers
N_CPUS = 2

# inflow rate at the highway
FLOW_RATE = 2000
# percent of autonomous vehicles
RL_PENETRATION = [0.1, 0.25, 0.33][EXP_NUM]
# num_rl term (see ADDITIONAL_ENV_PARAMs)
NUM_RL = [5, 13, 17][EXP_NUM]

# We consider a highway network with an upstream merging lane producing
# shockwaves
additional_net_params = ADDITIONAL_NET_PARAMS.copy()
# additional_net_params["merge_lanes"] = 1
# additional_net_params["highway_lanes"] = 1
# additional_net_params["pre_merge_length"] = 500

# RL vehicles constitute 5% of the total number of vehicles
vehicles = VehicleParams()
vehicles.add(
    veh_id="human",
    acceleration_controller=(IDMController, {
        "noise": 0.2
    }),
    car_following_params=SumoCarFollowingParams(
        speed_mode="obey_safe_speed",
    ),
    num_vehicles=5)
vehicles.add(
    veh_id="rl",
    acceleration_controller=(RLController, {}),
    car_following_params=SumoCarFollowingParams(
        speed_mode="obey_safe_speed",
    ),
    num_vehicles=5)

# Vehicles are introduced from both sides of merge, with RL vehicles entering
# from the highway portion as well
inflow = InFlows()
inflow.add(
    veh_type="human",
    edge="1",
    vehs_per_hour=(1 - RL_PENETRATION) * FLOW_RATE,
    departLane="free",
    departSpeed=10)
# inflow.add(
#     veh_type="rl",
#     edge="1",
#     vehs_per_hour=RL_PENETRATION * FLOW_RATE,
#     departLane="free",
#     departSpeed=10)
inflow.add(
    veh_type="human",
    edge="3",
    vehs_per_hour=100,
    departLane="free",
    departSpeed=7.5)

flow_params = dict(
    # name of the experiment
    exp_tag="stabilizing_open_network_merges",

    # name of the flow environment the experiment is running on
    env_name="BottleNeckAccelEnv",

    # name of the scenario class the experiment is running on
    scenario="BottleneckScenario",

    # simulator that is used by the experiment
    simulator='traci',

    # sumo-related parameters (see flow.core.params.SumoParams)
    sim=SumoParams(
        sim_step=0.2,
        render=False,
    ),

    # environment related parameters (see flow.core.params.EnvParams)
    env=EnvParams(
        horizon=HORIZON,
        sims_per_step=5,
        warmup_steps=0,
        additional_params={
            "max_accel": 1.5,
            "max_decel": 1.5,
            "target_velocity": 20,
            "num_rl": NUM_RL,
            "lane_change_duration": 5,
            "disable_tb": True,
            "disable_ramp_metering": True,
            "add_rl_if_exit": False,
        },
    ),

    # network-related parameters (see flow.core.params.NetParams and the
    # scenario's documentation or ADDITIONAL_NET_PARAMS component)
    net=NetParams(
        inflows=inflow,
        no_internal_links=False,
        additional_params=additional_net_params,
    ),

    # vehicles to be placed in the network at the start of a rollout (see
    # flow.core.vehicles.Vehicles)
    veh=vehicles,

    # parameters specifying the positioning of vehicles upon initialization/
    # reset (see flow.core.params.InitialConfig)
    initial=InitialConfig(),
)


def setup_exps():

    alg_run = "PPO"

    agent_cls = get_agent_class(alg_run)
    config = agent_cls._default_config.copy()
    config["num_workers"] = N_CPUS
    config["train_batch_size"] = HORIZON * N_ROLLOUTS
    config["gamma"] = 0.999  # discount rate
    config["model"].update({"fcnet_hiddens": [32, 32, 32]})
    config["use_gae"] = True
    config["lambda"] = 0.97
    config["kl_target"] = 0.02
    config["num_sgd_iter"] = 10
    config['clip_actions'] = False  # FIXME(ev) temporary ray bug
    config["horizon"] = HORIZON

    # save the flow params for replay
    flow_json = json.dumps(
        flow_params, cls=FlowParamsEncoder, sort_keys=True, indent=4)
    config['env_config']['flow_params'] = flow_json
    config['env_config']['run'] = alg_run

    create_env, gym_name = make_create_env(params=flow_params, version=0)

    # Register as rllib env
    register_env(gym_name, create_env)
    return alg_run, gym_name, config


if __name__ == "__main__":
    alg_run, gym_name, config = setup_exps()
    ray.init(num_cpus=N_CPUS + 1, redirect_output=False)
    trials = run_experiments({
        flow_params["exp_tag"]: {
            "run": alg_run,
            "env": gym_name,
            "config": {
                **config
            },
            "checkpoint_freq": 20,
            "max_failures": 999,
            "stop": {
                "training_iteration": 200,
            },
        }
    })

```

**Comment by pnp91** [comment] 2019-02-22 13:15
Hello @AboudyKreidieh 
Thanks a lot for the help. It worked for me. My experiment was successful. But I have a doubt. Why can we not add an inflow for vehicle type "rl"? Why is it removed? I tried running with it. But I was not successful. I want to is there a rule for the inflows to add

**Comment by AboudyKreidieh** [comment] 2019-02-25 21:56
hi @pnp91 sorry for the late reply. The issue is just a matter of the way the environment was written. Some other environemnts, however, do allow you to have an unfixed number of automated vehicles, see for example `WaveAttenuationMergePOEnv` in flow/envs/merge.py

Also, I noticed i didn't reply to your original question about details for creating custom environments. For that, I suggest you look into our tutorials: https://github.com/flow-project/flow/tree/master/tutorials

Hope this helps! Feel free to ask more about the details of any tutorial/example

**Comment by pnp91** [comment] 2019-02-26 09:22
Hi @AboudyKreidieh I sincerely thank you so much for taking out your time and helping a beginner as me. I know as a novice, my doubts may sound unwanted and simple. But still, thank you for taking out your time to help me understand. I appreciate a lot.

Also, I had gone through these tutorials and was trying to develop my own scenario with new environment and train with a new algorithm. So I wanted to analyse all the minute details on how to build this. I have also read the documentation on how to create a new env. But I was unclear with some small details. Hence I reached out here. May be that is where I failed and your answer now helped me. Thanks for being patient with me. It was little unclear in docs where the additional_parameter "add_rl_if_exit" was not mentioned explicitly. This made me little skeptic on how to proceed while creating new.

And now I am trying to change the algorithm from PPO to A3C in the same example. As mentioned in the docs, I have also changed the hyper-parameters in "default_config" as required. But still, I am not successful in this. Is there anything else apart from that which is required to be changed to make this successful?

**Comment by pnp91** [comment] 2019-02-26 13:52
@AboudyKreidieh Can I use a different algorithm instead of PPO as mentioned in all the examples of rllib? I wish to use A3C algorithm and had changed the snippet of code parameters as follows:

def setup_exps():

    alg_run = "A3C"

    agent_cls = get_agent_class(alg_run)
    config = agent_cls._default_config.copy()
    config["num_workers"] = N_CPUS
    config["sample_batch_size"] = HORIZON * N_ROLLOUTS
    config["gamma"] = 0.999  # discount rate
    config["lambda"] = 1.0
    config["grad_clip"] = 40.0
    config["lr"] = 0.0001
    config["lr_schedule"] = 0.0001
    config["vf_loss_coeff"] = 0.5
    config["entropy_coeff"] = -0.01
    config["sample_async"] = True
    config["min_iter_time_s"] = 5
    config["use_lstm"] = True
    config["horizon"] = HORIZON

    # save the flow params for replay
    flow_json = json.dumps(
        flow_params, cls=FlowParamsEncoder, sort_keys=True, indent=4)
    config['env_config']['flow_params'] = flow_json
    config['env_config']['run'] = alg_run

    create_env, gym_name = make_create_env(params=flow_params, version=0)

    # Register as rllib env
    register_env(gym_name, create_env)
    return alg_run, gym_name, config
-------------------------------------------------
But I encounter errors directing towards to tensor flow which is not used here. I have tried with other parameters as well. But nothing was helpful. Error still persists as follows:
**Error**:
-------
Traceback (most recent call last):
  File "A3C_Try.py", line 10, in <module>
    from ray.rllib.agents.agent import get_agent_class
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/__init__.py", line 9, in <module>
    from ray.tune.registry import register_trainable
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/__init__.py", line 6, in <module>
    from ray.tune.tune import run_experiments
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/tune.py", line 12, in <module>
    from ray.tune.suggest import BasicVariantGenerator
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/suggest/__init__.py", line 2, in <module>
    from ray.tune.suggest.basic_variant import BasicVariantGenerator
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/suggest/basic_variant.py", line 9, in <module>
    from ray.tune.config_parser import make_parser, create_trial_from_spec
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/config_parser.py", line 14, in <module>
    from ray.tune.trial import Trial, json_to_resources
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/trial.py", line 22, in <module>
    from ray.tune.logger import pretty_print, UnifiedLogger
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/logger.py", line 21, in <module>
    import tensorflow as tf
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 55, in <module>
    'tensorflow_estimator.python.estimator'))
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 64, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 66, in <module>
    from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 36, in <module>
    from tensorflow_estimator.python.estimator.export import export_lib
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/export/export_lib.py", line 25, in <module>
    from tensorflow.python.saved_model.model_utils import build_all_signature_defs
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/saved_model/model_utils/__init__.py", line 22, in <module>
    from tensorflow.python.saved_model.model_utils.export_utils import build_all_signature_defs
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.6/site-packages/tensorflow/python/saved_model/model_utils/export_utils.py", line 51, in <module>
    ModeKeys.TRAIN: signature_constants.DEFAULT_TRAIN_SIGNATURE_DEF_KEY,
AttributeError: module 'tensorflow.python.saved_model.signature_constants' has no attribute 'DEFAULT_TRAIN_SIGNATURE_DEF_KEY'

**Comment by AboudyKreidieh** [comment] 2019-02-28 23:12
hi @pnp91, first of happy to help whenever you need it! some details may not be very well documented, and issues like these help us identify some of the missing components in our codebase. Also, in terms of the A3C thing, can you share your new script (at least the A3C component) so that I can try it locally?

**Comment by pnp91** [comment] 2019-03-01 10:53
Hello @AboudyKreidieh thank you for your reply. Regarding A3C, I have now succeeded in implementing it. I will share the code as well. As per my investigation, I have realized that the problem was with the hyper parameter "train_batch_size". As per 'A3C-specific configs' stated in documentation [,](https://ray.readthedocs.io/en/latest/rllib-algorithms.html) it requires "sample_batch_size" parameter. Unfortunately, using this does not support in the algorithm for A3C. The parameter "train_batch_size" should be used in place of "sample_batch_size". Please correct me if my observations are incorrect. Attached below, is the code which I have modified to make it run: 
`
def setup_exps():

    alg_run = "A3C"

    agent_cls = get_agent_class(alg_run)
    config = agent_cls._default_config.copy()
    config["num_workers"] = N_CPUS
    config["train_batch_size"] = HORIZON * N_ROLLOUTS
    config["gamma"] = 0.999  # discount rate
    config["model"].update({"fcnet_hiddens": [64, 64]})
    config["lambda"] = 0.97
    config["horizon"] = HORIZON


    # save the flow params for replay
    flow_json = json.dumps(
        flow_params, cls=FlowParamsEncoder, sort_keys=True, indent=4)
    config['env_config']['flow_params'] = flow_json
    config['env_config']['run'] = alg_run

    create_env, gym_name = make_create_env(params=flow_params, version=0)

    # Register as rllib env
    register_env(gym_name, create_env)
    return alg_run, gym_name, config

if __name__ == "__main__":
    alg_run, gym_name, config = setup_exps()
    ray.init(num_cpus=N_CPUS + 1, redirect_output=False)
    trials = run_experiments({
        flow_params["exp_tag"]: {
            "run": alg_run,
            "env": gym_name,
            "config": {
                **config
            },
            "checkpoint_freq": 20,
            "max_failures": 999,
            "stop": {
                "training_iteration": 200,
            },
        }
    })`

**Comment by AboudyKreidieh** [comment] 2019-03-03 18:58
hi @pnp91 you are correct! the parameters tend to change from algorithm to algorithm in rllib. For those I would generally recommend looking into their documentation: https://ray.readthedocs.io/en/latest/rllib-algorithms.html

**Comment by AboudyKreidieh** [comment] 2019-05-18 00:32
assuming this has been resolved, so closing. feel free to open a new issue if anything else emerges!

**Closed by AboudyKreidieh** 2019-05-18 00:32 UTC
